export IOTHUB_DEVICE_SECURITY_TYPE='DPS'
export IOTHUB_DEVICE_DPS_ID_SCOPE='0ne006260BA'
export IOTHUB_DEVICE_DPS_DEVICE_ID='1rszxxqdsuv'
export IOTHUB_DEVICE_DPS_DEVICE_KEY='IH1mp1YGGQBDnBgKRrMDQ8xTZnOprdsn/a7xkHYgxfI='
python3.7 main.py