from matplotlib.pyplot import plt
fig = plt.figure(figsize=(10,5))
# for sensor data from a dictionary
plt.plot(sensor_dict['a_mean'], label='a_mean')
plt.plot(sensor_dict['a_std'], label='a_std')
plt.plot(sensor_dict['a_maxx'], label='a_maxx')
plt.plot(sensor_dict['a_maxx'], label='a_maxy')
plt.plot(sensor_dict['a_maxx'], label='a_maxz')
plt.plot(sensor_dict['e_max'], label='e_max')
plt.plot(sensor_dict['e_min'], label='e_min')
plt.plot(sensor_dict['e_mean'], label='e_mean')
plt.plot(sensor_dict['e_range'], label='e_range')
plt.plot(sensor_dict['e_std'], label='e_std')
plt.plot(sensor_dict['t_max'], label='t_max')
plt.plot(sensor_dict['t_mean'], label='t_mean')
plt.legend(loc='upper right')
fig.savefig("corr.png")
plt.show()
#for wesad data
#fig = plt.figure(figsize=(10,5))
#plt.plot(manager.STRESS_FEATURES['a_mean'], label='a_mean')
#plt.plot(manager.STRESS_FEATURES['a_std'], label='a_std')
#plt.plot(manager.STRESS_FEATURES['a_maxx'], label='a_maxx')
#plt.plot(manager.STRESS_FEATURES['a_maxx'], label='a_maxy')
#plt.plot(manager.STRESS_FEATURES['a_maxx'], label='a_maxz')
#plt.plot(manager.STRESS_FEATURES['e_max'], label='e_max')
#plt.plot(manager.STRESS_FEATURES['e_min'], label='e_min')
#plt.plot(manager.STRESS_FEATURES['e_mean'], label='e_mean')
#plt.plot(manager.STRESS_FEATURES['e_range'], label='e_range')
#plt.plot(manager.STRESS_FEATURES['e_std'], label='e_std')
#plt.plot(manager.STRESS_FEATURES['t_max'], label='t_max')
#plt.plot(manager.STRESS_FEATURES['t_mean'], label='t_mean')
#plt.legend(loc='upper right')
#fig.savefig("corr.png")
#plt.show()
